### ISSUE TITLE
autodownload onix,luconia and latite

### ISSUE THREAD

**Issue by fifomitch** [ignYoqzii/StarZLauncher#1]
can you make it so it just auto downloads onix client,luconia and latite because i think it would mkae it better if it just auto downloads all the clients when you download starZ

**Comment by ignYoqzii** [comment]
I will have to check for that. I'm not sure if I can...

**Comment by ignYoqzii** [comment]
I will do it when I will have the appx's and the version selector ready

**Comment by fifomitch** [comment]
ok
